### ISSUE TITLE
Support for Acronym Keys

### ISSUE THREAD

**Issue by sshaw** [futurechimp/awrence#1]
In some case one needs`{:site_url => "...", :user_id => 1}`  to be `{siteURL => "...", userID => 1}`. This is not possible. 

What about adding something like: 

```rb
# bad name but you get the idea
Awrence.mappings = { :url => "URL", ... }
```
❓

**Comment by futurechimp** [comment]
Hi @sshaw,  I don't have time at the moment to do this myself, but a pull request would be really welcome.

**Comment by sleepingstu** [comment]
Closing as now merged the PR. Will release a new gem version soon.
